name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      api-directory: ./api
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Deploy API
      run: docker-compose up -d --build
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '300s'
    - name: Check running containers
      run: docker ps
    - name: Check containters log
      run: docker-compose logs
    - name: Test index endpoint
      run: curl -f http://localhost:8080/ | grep "Welcome to Casescan API!" || exit 1
