name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      api-directory: ./api
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      working-directory: ${{env.api-directory}}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.lock ]; then pip install -r requirements.lock; fi
    - name: Lint with flake8
      working-directory: ${{env.api-directory}}
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Deploy API
      run: docker-compose up -d --build
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '300s'
    - name: Check running containers
      run: docker ps
    - name: Check containters log
      run: docker-compose logs
    - name: Test index endpoint
      run: curl -f http://localhost:8080/ | grep "Welcome to Casescan API!" || exit 1
