name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "casescan"
          heroku_email: "alsumo95@gmail.com"
          usedocker: true
          appdir: "api"
          healthcheck: "https://casescan.herokuapp.com"
          delay: 300
          rollbackonhealthcheckfailed: true
          dontuseforce: true
